version: "3.9"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - model-service

  model-service:
    build: 
      context: ./model-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./model-service/models:/app/models
      - ./model-service/knowledge:/app/knowledge
